  # MySQL
  defaults: &defaults
    host: localhost
    port: 3306
    username: development
    password: P@ssw0rd!
    adapter: mysql2

  development:
    <<: *defaults
    database: certtracker_dev

  test:
    <<: *defaults
    database: certtracker_dev

  production:
    <<: *defaults
    database: certtracker_prod
